disabled_rules:
  #- block_based_kvo
  #- class_delegate_protocol
  #- closure_parameter_position
  #- compiler_protocol_init
  #- control_statement
  - custom_rules
  #- cyclomatic_complexity
  #- discarded_notification_center_observer
  #- discouraged_direct_init
  #- dynamic_inline
  ##- empty_enum_arguments
  ##- empty_parameters
  ##- empty_parentheses_with_trailing_closure
  #- file_length
  #- for_where
  #- force_cast
  #- force_try
  #- function_body_length
  #- function_parameter_count
  #- generic_type_name
  #- identifier_name
  #- implicit_getter
  #- is_disjoint
  #- large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  #- line_length
  ##- mark
  #- multiple_closures_with_trailing_closure
  #- nesting
  #- notification_center_detachment
  ##- opening_brace
  #- operator_whitespace
  - private_over_fileprivate
  #- private_unit_test
  ##- protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  ##- return_arrow_whitespace
  #- shorthand_operator
  ##- statement_position
  #- superfluous_disable_command
  #- switch_case_alignment
  #- syntactic_sugar
  #- todo
  - trailing_comma
  - trailing_semicolon
  #- type_body_length
  #- type_name
  #- unneeded_break_in_switch
  - unused_closure_parameter
  #- unused_enumerated
  #- unused_optional_binding
  #- valid_ibinspectable
  #- vertical_parameter_alignment
  - void_return
  #- weak_delegate
  #- xctfail_message
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - unneeded_parentheses_in_closure_argument
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - External
