language:
  - swift
osx_image: xcode10.2
script:
  - xcodebuild -workspace Movies24i.xcworkspace -scheme Movies24i -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' build test
